version: 2.0

defaults: &defaults
    docker:
        - image: python:alpine3.6

jobs:
    test:
        <<: *defaults
        name: Test Tukio
        steps:
            - checkout
            - run:
                name: Install dependencies
                command: |
                    mkdir -p /tmp/test-results
                    pip install -U .
                    pip install -r requirements_test.txt
            - run:
                name: Run unittests
                command: nosetests --with-xunit --xunit-file=/tmp/test-results/xunit.xml --cover-branches --with-coverage --cover-erase --cover-package=tukio --cover-html --cover-html-dir=/tmp/test-results/coverage
            - store_test_results:
                path: /tmp/test-results
    deploy:
        <<: *defaults
        name: Deploy Tukio to Pypi
        steps:
            - checkout
            - run:
                name: Install Twine
                command: pip install -U twine
            - run:
                name: Build and deploy Tukio's package
                command: ./deploy_to_pypi.sh

workflows:
    version: 2
    test-deploy:
        jobs:
            - test
            - deploy:
                requires:
                    - test
                filters:
                    tags:
                        only: /[0-9]+(\.[0-9]+){2}/
